// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  amenities: dynamic(() => import("./Amenities")),
  call_to_action: dynamic(() => import("./CallToAction")),
  hero: dynamic(() => import("./Hero")),
  navigation_item: dynamic(() => import("./NavigationItem")),
  rich_text: dynamic(() => import("./RichText")),
};
